name: Create Release Pull Request
on: [workflow_dispatch]
jobs:
  createReleasePullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%Y-%m-%d@%H_%M_%S')"

      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset develop branch
        run: |
         git fetch origin develop:develop
         git reset --hard develop
      - name: Create Release Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: release/${{ steps.date.outputs.date }}
          title: 'New Release ${{ steps.date.outputs.date }} ğŸš€'
          body: |
            This release was made with â¤ï¸ automatically by the create release pull request action ğŸ’ª
          draft: false
      - uses: ./.github/workflows/branch-name
      - uses: ./.github/workflows/reviewdog
      - uses: ./.github/workflows/auto-approve
