name: Memer Workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASE_SLAYER_APP_ID }}
          private_key: ${{ secrets.RELEASE_SLAYER_APP_SECRET }}

      - uses: actions/checkout@master
      - name: Run Memer Action
        id: memer

        uses: Bhupesh-V/memer-action@master
        with:
          filter: "new"
          fallback: '{"meme_link":"https://pbs.twimg.com/media/EOb_2m4W4AYDf-p.jpg", "title": "Oops :( looks like we are out of memes.", "src": ""}'

      - name: Check Outputs
        run: |
          echo "${{ steps.memer.outputs.meme }}"
          echo "${{ steps.memer.outputs.title }}"
          echo "${{ steps.memer.outputs.source }}"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1.3.0
        id: couc
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ðŸŽ‰ðŸŽ‰ Thanks for opening this PR ðŸ¤—
            Please wait while a developer review it

            Meanwhile have a look at this ðŸ˜ :

            > **${{ steps.memer.outputs.title }}**
            ![meme](${{ steps.memer.outputs.meme }})
          token: ${{ steps.generate-token.outputs.token }}
